Sequlite::ALF::MotionControl::MotionController
RecordsUpdateHandler Sequlite.ALF.MotionControl.MotionController.OnRecordsUpdated
HywireGalilControl Sequlite.ALF.MotionControl.MotionController._HywireController
MagellanControl Sequlite.ALF.MotionControl.MotionController._MagellanController
bool Sequlite.ALF.MotionControl.MotionController._IsGalilConnected
bool Sequlite.ALF.MotionControl.MotionController._IsMagellanConnected
System.Timers.Timer Sequlite.ALF.MotionControl.MotionController._RecordTimer
HywireController Sequlite.ALF.MotionControl.MotionController._HywireMotionController
bool Sequlite.ALF.MotionControl.MotionController.UsingHywireController
Referenced by Sequlite.ALF.EngineerGUI.ViewModel.MotionViewModel.ExecuteRelativeMoveCmd.
bool Sequlite.ALF.MotionControl.MotionController.IsGalilConnected
bool Sequlite.ALF.MotionControl.MotionController.IsZStageConnected
int Sequlite.ALF.MotionControl.MotionController.FCurrentPos
int Sequlite.ALF.MotionControl.MotionController.YCurrentPos
double Sequlite.ALF.MotionControl.MotionController.ZCurrentPos
Z current position, unit of um
int Sequlite.ALF.MotionControl.MotionController.CCurrentPos
bool Sequlite.ALF.MotionControl.MotionController.IsFAtHome
bool Sequlite.ALF.MotionControl.MotionController.IsYAtHome
bool Sequlite.ALF.MotionControl.MotionController.IsZAtHome
bool Sequlite.ALF.MotionControl.MotionController.IsFAtLimit
bool Sequlite.ALF.MotionControl.MotionController.IsYAtLimit
bool Sequlite.ALF.MotionControl.MotionController.IsZAtLimit
delegate void Sequlite.ALF.MotionControl.MotionController.RecordsUpdateHandler()
Sequlite.ALF.MotionControl.MotionController.MotionController()
void Sequlite.ALF.MotionControl.MotionController.ZStageConnect()
void Sequlite.ALF.MotionControl.MotionController.OtherStagesConnect()
bool Sequlite.ALF.MotionControl.MotionController.SendCommand(string cmd)
bool Sequlite.ALF.MotionControl.MotionController.HomeMotion(MotionTypes type, int speed, int accel, bool wait)
References Sequlite.ALF.MotionControl.GalilControl.Commands.
Referenced by Sequlite.ALF.EngineerGUI.ViewModel.MotionViewModel.ExecuteHomeCmd.
bool Sequlite.ALF.MotionControl.MotionController.HomeZstage()
speed unit: um/sec accel unit: um/sec^2 wait
Referenced by Sequlite.ALF.EngineerGUI.ViewModel.MotionViewModel.ExecuteHomeCmd.
bool Sequlite.ALF.MotionControl.MotionController.AbsoluteMove(MotionTypes type, int pos, int speed, int accel, bool wait=false)
References Sequlite.ALF.MotionControl.GalilControl.Commands.
Referenced by Sequlite.ALF.EngineerGUI.ViewModel.MotionViewModel.ExecuteAbsoluteMoveCmd.
bool Sequlite.ALF.MotionControl.MotionController.AbsoluteMoveZStage(double pos, double speed, double accel, bool wait=false)
pos unit: um speed unit: um/sec accel unit: um/sec^2 wait
Referenced by Sequlite.ALF.EngineerGUI.ViewModel.MotionViewModel.ExecuteAbsoluteMoveCmd.
bool Sequlite.ALF.MotionControl.MotionController.RelativeMove(MotionTypes type, int pos, int speed, int accel, bool wait=false)
References Sequlite.ALF.MotionControl.GalilControl.Commands.
bool Sequlite.ALF.MotionControl.MotionController.RelativeMoveZStage(double pos, double speed, double accel, bool wait=false)
pos unit: um speed unit: um/sec accel unit: um/sec^2 wait
bool Sequlite.ALF.MotionControl.MotionController.HaltAllMotions()
bool Sequlite.ALF.MotionControl.MotionController.HaltZStage()
bool Sequlite.ALF.MotionControl.MotionController.SelectFilter(int filter, bool wait=false)
References Sequlite.ALF.Configuration.SettingsManager.ConfigSettings, Sequlite.ALF.Configuration.ConfigSettings.FilterPositions, Sequlite.ALF.Configuration.ConfigSettings.MotionStartupSettings.
void Sequlite.ALF.MotionControl.MotionController._RecordTimer_Elapsed(object sender, System.Timers.ElapsedEventArgs e)