Photometrics::Pvcam::PVCAM
bool Photometrics.Pvcam.PVCAM.m_is64bit
Referenced by Photometrics.Pvcam.PVCAM.pl_cam_close, Photometrics.Pvcam.PVCAM.pl_cam_deregister_callback, Photometrics.Pvcam.PVCAM.pl_cam_get_name, Photometrics.Pvcam.PVCAM.pl_cam_get_total, Photometrics.Pvcam.PVCAM.pl_cam_open, Photometrics.Pvcam.PVCAM.pl_cam_register_callback, Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex, Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex2, Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex3, Photometrics.Pvcam.PVCAM.pl_create_frame_info_struct, Photometrics.Pvcam.PVCAM.pl_create_smart_stream_struct, Photometrics.Pvcam.PVCAM.pl_enum_str_length, Photometrics.Pvcam.PVCAM.pl_error_code, Photometrics.Pvcam.PVCAM.pl_error_message, Photometrics.Pvcam.PVCAM.pl_exp_abort, Photometrics.Pvcam.PVCAM.pl_exp_check_cont_status, Photometrics.Pvcam.PVCAM.pl_exp_check_cont_status_ex, Photometrics.Pvcam.PVCAM.pl_exp_check_status, Photometrics.Pvcam.PVCAM.pl_exp_finish_seq, Photometrics.Pvcam.PVCAM.pl_exp_get_latest_frame, Photometrics.Pvcam.PVCAM.pl_exp_get_latest_frame_ex, Photometrics.Pvcam.PVCAM.pl_exp_get_oldest_frame, Photometrics.Pvcam.PVCAM.pl_exp_get_oldest_frame_ex, Photometrics.Pvcam.PVCAM.pl_exp_init_seq, Photometrics.Pvcam.PVCAM.pl_exp_setup_cont, Photometrics.Pvcam.PVCAM.pl_exp_setup_seq, Photometrics.Pvcam.PVCAM.pl_exp_start_cont, Photometrics.Pvcam.PVCAM.pl_exp_start_seq, Photometrics.Pvcam.PVCAM.pl_exp_stop_cont, Photometrics.Pvcam.PVCAM.pl_exp_uninit_seq, Photometrics.Pvcam.PVCAM.pl_exp_unlock_oldest_frame, Photometrics.Pvcam.PVCAM.pl_get_enum_param, Photometrics.Pvcam.PVCAM.pl_get_param, Photometrics.Pvcam.PVCAM.pl_md_create_frame_struct, Photometrics.Pvcam.PVCAM.pl_md_create_frame_struct_cont, Photometrics.Pvcam.PVCAM.pl_md_frame_decode, Photometrics.Pvcam.PVCAM.pl_md_frame_recompose, Photometrics.Pvcam.PVCAM.pl_md_release_frame_struct, Photometrics.Pvcam.PVCAM.pl_pp_reset, Photometrics.Pvcam.PVCAM.pl_pvcam_get_ver, Photometrics.Pvcam.PVCAM.pl_pvcam_init, Photometrics.Pvcam.PVCAM.pl_pvcam_uninit, Photometrics.Pvcam.PVCAM.pl_release_frame_info_struct, Photometrics.Pvcam.PVCAM.pl_release_smart_stream_struct, Photometrics.Pvcam.PVCAM.pl_set_param, Photometrics.Pvcam.PVCAM.PVCAM.
static Photometrics.Pvcam.PVCAM.PVCAM()
A static constructor is called automatically to initialize the class before the first instance is created or any static members are referenced.
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_pvcam_init()
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.RefreshCameras.
static bool Photometrics.Pvcam.PVCAM.pl_pvcam_uninit()
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_pvcam_get_ver(out UInt16 version)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.RefreshCameras.
static bool Photometrics.Pvcam.PVCAM.pl_cam_close(Int16 hCam)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.CloseCamera.
static bool Photometrics.Pvcam.PVCAM.pl_cam_get_name(Int16 cameraNumber, StringBuilder cameraName)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.RefreshCameras.
static bool Photometrics.Pvcam.PVCAM.pl_cam_get_total(out Int16 hCam)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.RefreshCameras.
static bool Photometrics.Pvcam.PVCAM.pl_cam_open(StringBuilder cameraName, out Int16 hCam, PvTypes.CameraOpenMode o_mode)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.OpenCamera.
static bool Photometrics.Pvcam.PVCAM.pl_cam_register_callback(Int16 hCam, PvTypes.PL_CALLBACK_EVENT callBackEvent, PvTypes.PMCallBack callback)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex(Int16 hCam, PvTypes.PL_CALLBACK_EVENT callBackEvent, PvTypes.PMCallBack_Ex callback, IntPtr context)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex2(Int16 hCam, PvTypes.PL_CALLBACK_EVENT callBackEvent, PvTypes.PMCallBack_Ex2 callback)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_cam_register_callback_ex3(Int16 hCam, PvTypes.PL_CALLBACK_EVENT callBackEvent, PvTypes.PMCallBack_Ex3 callback, IntPtr context)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.AcqSetup.
static bool Photometrics.Pvcam.PVCAM.pl_cam_deregister_callback(Int16 hCam, PvTypes.PL_CALLBACK_EVENT callBackEvent)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static Int16 Photometrics.Pvcam.PVCAM.pl_error_code()
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_error_message(Int16 err_code, StringBuilder msg)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_get_param(Int16 hcam, UInt32 param_id, Int16 param_attrib, IntPtr param_value)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.BuildSpeedTable, Sequlite.CameraLib.PVCamCamera.ConfigPostProcessingID, Sequlite.CameraLib.PVCamCamera.GetCameraInformation, Sequlite.CameraLib.PVCamCamera.GetCurrentTemprature, Sequlite.CameraLib.PVCamCamera.GetEstReadoutTime, Sequlite.CameraLib.PVCamCamera.GetFirmwareVersion, Sequlite.CameraLib.PVCamCamera.isParamAvailable, Sequlite.CameraLib.PVCamCamera.ReadCameraParams, Sequlite.CameraLib.PVCamCamera.ReadCentroidParameters, Sequlite.CameraLib.PVCamCamera.ReadCoolingParameters, Sequlite.CameraLib.PVCamCamera.ReadEnumeration, Sequlite.CameraLib.PVCamCamera.ReadExpTimeRange, Sequlite.CameraLib.PVCamCamera.ReadFanSpeedParameters, Sequlite.CameraLib.PVCamCamera.ReadPostProcessingFeatures, Sequlite.CameraLib.PVCamCamera.ReadRegionParameters, Sequlite.CameraLib.PVCamCamera.SetSmartStreaming.
static bool Photometrics.Pvcam.PVCAM.pl_set_param(Int16 hcam, UInt32 param_id, IntPtr param_value)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.BuildSpeedTable, Sequlite.CameraLib.PVCamCamera.ConfigPostProcessingID, Sequlite.CameraLib.PVCamCamera.ConfigureMetadata, Sequlite.CameraLib.PVCamCamera.ReadPostProcessingFeatures, Sequlite.CameraLib.PVCamCamera.SetCentroiding, Sequlite.CameraLib.PVCamCamera.SetClearCycles, Sequlite.CameraLib.PVCamCamera.SetClearMode, Sequlite.CameraLib.PVCamCamera.SetClockingMode, Sequlite.CameraLib.PVCamCamera.SetEMGain, Sequlite.CameraLib.PVCamCamera.SetFanSpeedSetpoint, Sequlite.CameraLib.PVCamCamera.SetGainState, Sequlite.CameraLib.PVCamCamera.SetReadoutSpeed, Sequlite.CameraLib.PVCamCamera.SetShutterMode, Sequlite.CameraLib.PVCamCamera.SetSmartStreaming, Sequlite.CameraLib.PVCamCamera.SetTemperatureSetpoint, Sequlite.CameraLib.PVCamCamera.UpdatePostProceesingFeature, Sequlite.CameraLib.PVCamCamera.WritePostProcessingFeature.
static bool Photometrics.Pvcam.PVCAM.pl_get_enum_param(Int16 hcam, UInt32 param_id, UInt32 index, out Int32 value, StringBuilder desc, UInt32 length)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.ReadEnumeration.
static bool Photometrics.Pvcam.PVCAM.pl_enum_str_length(Int16 hcam, UInt32 param_id, UInt32 index, out UInt32 length)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.ReadEnumeration.
static bool Photometrics.Pvcam.PVCAM.pl_pp_reset(Int16 hcam)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_create_smart_stream_struct(out PvTypes.smart_stream_type smtStreamStruct, UInt16 entries)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_release_smart_stream_struct(out PvTypes.smart_stream_type smtStreamStruct)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_create_frame_info_struct(out PvTypes.FRAME_INFO new_frame)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_release_frame_info_struct(PvTypes.FRAME_INFO frame_to_delete)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_init_seq()
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_setup_seq(Int16 hcam, UInt16 exp_total, UInt16 rgn_total, ref PvTypes.RegionType rgn_array, Int16 mode, UInt32 exposure_time, out UInt32 stream_size)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.AcqSetup.
static bool Photometrics.Pvcam.PVCAM.pl_exp_start_seq(Int16 hcam, IntPtr pixel_stream_ptr)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.StartSeqAcq, Sequlite.CameraLib.PVCamCamera.StartSyncSeqAcq.
static bool Photometrics.Pvcam.PVCAM.pl_exp_check_status(Int16 hcam, out Int16 status, out UInt32 byte_cnt)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.SingleAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_exp_uninit_seq()
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_finish_seq(Int16 hcam, IntPtr pixel_stream_ptr, Int16 hbuf)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_abort(Int16 hcam, Int16 cam_state)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.StopAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_exp_start_cont(Int16 hcam, IntPtr pixel_stream, UInt32 size)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.StartContinuousAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_exp_setup_cont(Int16 hcam, UInt16 rgn_total, ref PvTypes.RegionType rgn_array, Int16 mode, UInt32 exposure_time, out UInt32 stream_size, Int16 circ_mode)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.AcqSetup.
static bool Photometrics.Pvcam.PVCAM.pl_exp_get_latest_frame(Int16 hcam, out IntPtr frame)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_get_latest_frame_ex(Int16 hcam, out IntPtr frame, out PvTypes.FRAME_INFO pFrameInfo)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.GetNewFrame.
static bool Photometrics.Pvcam.PVCAM.pl_exp_get_oldest_frame(Int16 hcam, out IntPtr frame)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_get_oldest_frame_ex(Int16 hcam, out IntPtr frame, out PvTypes.FRAME_INFO pFrameInfo)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_check_cont_status(Int16 hcam, out Int16 status, out UInt32 byte_cnt, out UInt32 buffer_cnt)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_check_cont_status_ex(Int16 hcam, out Int16 status, out UInt32 byte_cnt, out UInt32 buffer_cnt, out PvTypes.FRAME_INFO pFrameInfo)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_exp_stop_cont(Int16 hcam, Int16 cam_state)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.StopAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_exp_unlock_oldest_frame(Int16 hcam)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_md_frame_decode(IntPtr pDstFrame, IntPtr pSrcBuf, UInt32 srcBufSize)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.GetNewFrame, Sequlite.CameraLib.PVCamCamera.SingleAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_md_frame_recompose(IntPtr pDstBuf, UInt16 offX, UInt16 offY, UInt16 dstWidth, UInt16 dstHeight, ref PvTypes.MD_Frame pSrcFrame)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.GetNewFrame, Sequlite.CameraLib.PVCamCamera.SingleAcquisition.
static bool Photometrics.Pvcam.PVCAM.pl_md_create_frame_struct_cont(ref IntPtr pFrame, UInt16 roiCount)
References Photometrics.Pvcam.PVCAM.m_is64bit.
Referenced by Sequlite.CameraLib.PVCamCamera.CreateMetadataStructure.
static bool Photometrics.Pvcam.PVCAM.pl_md_create_frame_struct(ref IntPtr pFrame, IntPtr pSrcBuf, UInt32 srcBufSize)
References Photometrics.Pvcam.PVCAM.m_is64bit.
static bool Photometrics.Pvcam.PVCAM.pl_md_release_frame_struct(IntPtr pFrame)
References Photometrics.Pvcam.PVCAM.m_is64bit.