//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequlite.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sequlite.UI.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and  Confirm Run Setup Parameters.
        /// </summary>
        internal static string CheckPage_Description_0 {
            get {
                return ResourceManager.GetString("CheckPage_Description_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Hardware Conditions before Run.
        /// </summary>
        internal static string CheckPage_Description_1 {
            get {
                return ResourceManager.GetString("CheckPage_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the Flow Cell.
        /// </summary>
        internal static string LoadPage_Description_0 {
            get {
                return ResourceManager.GetString("LoadPage_Description_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the Reagent Cartridge.
        /// </summary>
        internal static string LoadPage_Description_1 {
            get {
                return ResourceManager.GetString("LoadPage_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the Buffer Cartridge.
        /// </summary>
        internal static string LoadPage_Description_2 {
            get {
                return ResourceManager.GetString("LoadPage_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the Waste Bottle.
        /// </summary>
        internal static string LoadPage_Description_3 {
            get {
                return ResourceManager.GetString("LoadPage_Description_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Wash After Sequence.
        /// </summary>
        internal static string PostRunPage_Description {
            get {
                return ResourceManager.GetString("PostRunPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up Run Parameters.
        /// </summary>
        internal static string RunSetupPage_Description {
            get {
                return ResourceManager.GetString("RunSetupPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Sequence.
        /// </summary>
        internal static string SequencePage_Description {
            get {
                return ResourceManager.GetString("SequencePage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Summary Information.
        /// </summary>
        internal static string SummaryPage_Description_0 {
            get {
                return ResourceManager.GetString("SummaryPage_Description_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Run Result in  Charts &amp; Graphs.
        /// </summary>
        internal static string SummaryPage_Description_1 {
            get {
                return ResourceManager.GetString("SummaryPage_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Sample Sheet Information.
        /// </summary>
        internal static string SummaryPage_Description_2 {
            get {
                return ResourceManager.GetString("SummaryPage_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Information.
        /// </summary>
        internal static string UserPage_Description {
            get {
                return ResourceManager.GetString("UserPage_Description", resourceCulture);
            }
        }
    }
}
