//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequlite.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sequlite.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ApplicationMainWindow_Button_Data {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ApplicationMainWindow_Button_Exit {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        public static string ApplicationMainWindow_Button_RunEngineering {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_RunEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string ApplicationMainWindow_Button_RunMaintenance {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_RunMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string ApplicationMainWindow_Button_RunSequence {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_RunSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ApplicationMainWindow_Button_RunSettings {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_RunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequlite Software.
        /// </summary>
        public static string ApplicationMainWindow_Title {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string PageDisplayName_Check {
            get {
                return ResourceManager.GetString("PageDisplayName_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Hardware.
        /// </summary>
        public static string PageDisplayName_Check_Hardware {
            get {
                return ResourceManager.GetString("PageDisplayName_Check_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Parameters.
        /// </summary>
        public static string PageDisplayName_Check_RunParams {
            get {
                return ResourceManager.GetString("PageDisplayName_Check_RunParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string PageDisplayName_Load {
            get {
                return ResourceManager.GetString("PageDisplayName_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        public static string PageDisplayName_Load_Buffer {
            get {
                return ResourceManager.GetString("PageDisplayName_Load_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Cell.
        /// </summary>
        public static string PageDisplayName_Load_FlowCell {
            get {
                return ResourceManager.GetString("PageDisplayName_Load_FlowCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagents.
        /// </summary>
        public static string PageDisplayName_Load_Reagents {
            get {
                return ResourceManager.GetString("PageDisplayName_Load_Reagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string PageDisplayName_Load_Waste {
            get {
                return ResourceManager.GetString("PageDisplayName_Load_Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Run.
        /// </summary>
        public static string PageDisplayName_PostRun {
            get {
                return ResourceManager.GetString("PageDisplayName_PostRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Setup.
        /// </summary>
        public static string PageDisplayName_RunSetup {
            get {
                return ResourceManager.GetString("PageDisplayName_RunSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string PageDisplayName_Seqence {
            get {
                return ResourceManager.GetString("PageDisplayName_Seqence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PageDisplayName_Summary {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts &amp; Graphs.
        /// </summary>
        public static string PageDisplayName_Summary_Charts_Graphs {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary_Charts_Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Summary.
        /// </summary>
        public static string PageDisplayName_Summary_Run {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sheet.
        /// </summary>
        public static string PageDisplayName_Summary_SampleSheet {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary_SampleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string PageDisplayName_User {
            get {
                return ResourceManager.GetString("PageDisplayName_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sequlite Software.
        /// </summary>
        public static string PageDisplayName_Welcome {
            get {
                return ResourceManager.GetString("PageDisplayName_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View / Open.
        /// </summary>
        public static string RunSetupPage_Button_View {
            get {
                return ResourceManager.GetString("RunSetupPage_Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Primers:.
        /// </summary>
        public static string RunSetupPage_CustomPrimers {
            get {
                return ResourceManager.GetString("RunSetupPage_CustomPrimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string RunSetupPage_Dscription {
            get {
                return ResourceManager.GetString("RunSetupPage_Dscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 1.
        /// </summary>
        public static string RunSetupPage_Index1 {
            get {
                return ResourceManager.GetString("RunSetupPage_Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index 2.
        /// </summary>
        public static string RunSetupPage_Index2 {
            get {
                return ResourceManager.GetString("RunSetupPage_Index2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read 1.
        /// </summary>
        public static string RunSetupPage_Read1 {
            get {
                return ResourceManager.GetString("RunSetupPage_Read1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read 2.
        /// </summary>
        public static string RunSetupPage_Read2 {
            get {
                return ResourceManager.GetString("RunSetupPage_Read2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads:.
        /// </summary>
        public static string RunSetupPage_Reads {
            get {
                return ResourceManager.GetString("RunSetupPage_Reads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Name:.
        /// </summary>
        public static string RunSetupPage_RunName {
            get {
                return ResourceManager.GetString("RunSetupPage_RunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Sheet:.
        /// </summary>
        public static string RunSetupPage_SampleSheet {
            get {
                return ResourceManager.GetString("RunSetupPage_SampleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SeqenceWizardView_Button_Cancel {
            get {
                return ResourceManager.GetString("SeqenceWizardView_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Run.
        /// </summary>
        public static string SeqenceWizardView_Button_Cancel_StopRun {
            get {
                return ResourceManager.GetString("SeqenceWizardView_Button_Cancel_StopRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string SequenceWizardView_Button_Finish {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string SequenceWizardView_Button_MoveNext {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string SequenceWizardView_Button_MoveNext_Confirm {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_MoveNext_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Again.
        /// </summary>
        public static string SequenceWizardView_Button_MoveNext_RunCheck {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_MoveNext_RunCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string SequenceWizardView_Button_MovePrevious {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Data.
        /// </summary>
        public static string SequenceWizardView_Button_MovePrevious_UploadData {
            get {
                return ResourceManager.GetString("SequenceWizardView_Button_MovePrevious_UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string SequenceWizardView_Header_Steps {
            get {
                return ResourceManager.GetString("SequenceWizardView_Header_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SequnceWizardView_Label_Status {
            get {
                return ResourceManager.GetString("SequnceWizardView_Label_Status", resourceCulture);
            }
        }
    }
}
